Module6 task1
htmlacademy-yii/221665-task-force-1 pull request #11
Opened 2020-09-15 18:43 UTC by balesniy

2020-09-15 18:45 UTC, balesniy commented
Кирилл, привет. вроде с идеей формы разобрался, но с реализацией не справился - разметка летит, как починить не придумал, в частности как вынести инпуты и убрать обертки. направь пожалуйста, в какую сторону копать.

2020-09-16 07:03 UTC, frexin requested changes

2020-09-16 07:03 UTC, frexin commented on common/config/main.php
> +            'rules' => [
Можно заменить одним правилом: `'<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>'`

2020-09-16 07:03 UTC, frexin commented on frontend/controllers/TasksController.php
> +        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
Валидация тут не обязательна, но можешь оставить

2020-09-16 07:03 UTC, frexin commented on frontend/controllers/TasksController.php
> +        } else {
Ну и вообще все эти условия не нужны

2020-09-16 07:03 UTC, frexin commented on frontend/controllers/TasksController.php
> +    public function actionFilter()
Зачем делать отдельный экшн для фильтрации?

2020-09-16 07:03 UTC, frexin commented on frontend/views/tasks/index.php
> +                ['itemOptions' => ['class' => 'visually-hidden checkbox__input'],]
Тут тебе проще всего будет вообще убрать второй аргумент. Ты все сделал правильно, но тут выяснилось, что верстку этих чекбоксов невозможно интегрировать правильно средствами Yii.

2020-09-16 07:04 UTC, frexin commented
Поправь там всякие мелочи и сделай фильтрацию на странице пользователей

2020-09-16 07:05 UTC, frexin requested changes

2020-09-16 07:05 UTC, frexin commented on frontend/views/tasks/index.php
> +            <?= $form->field($model, 'categories[]')->checkboxList($model->getCategories(),
Здесь нужно просто `categories`

2020-09-16 07:07 UTC, frexin requested changes

2020-09-16 07:07 UTC, frexin commented on frontend/models/TaskForm.php
> +    public function getTasks() {
Нужно добавить фильтрацию по периоду

2020-09-17 11:01 UTC, balesniy commented on frontend/views/tasks/index.php
> +            <?= $form->field($model, 'categories[]')->checkboxList($model->getCategories(),
я взял пример из доки, подскажи пожалуйста, в чем тут ошибка? https://www.yiiframework.com/doc/guide/2.0/ru/input-forms#sozdanie-form

2020-09-17 15:46 UTC, frexin commented on frontend/views/tasks/index.php
> +            <?= $form->field($model, 'categories[]')->checkboxList($model->getCategories(),
Ошибка в документации, видимо. Потому что без `[]` все работает отлично

2020-09-21 08:02 UTC, frexin requested changes

2020-09-21 08:02 UTC, frexin commented on frontend/models/UserForm.php
> +                ->having(['=', 'count(distinct uc.category_id)', count($this->categories)]); // todo не придумал как еще выбрать все категории
having не нужен, группировка не нужна. Делаешь joinWith с нужной связью и добавляешь условие в where

2020-09-21 08:02 UTC, frexin commented on frontend/models/UserForm.php
> +            $users->leftJoin('favorites f', 'users.id = f.selected_user_id')
Определяешь связь с избранным. Делаешь и делаешь inner join джойн с этой связью. Больше ничего не нужно

2020-09-21 08:02 UTC, frexin commented on frontend/models/UserForm.php
> +            $users->addGroupBy('name')->andHaving('count(c.id) > 0');
При таких запросах у тебя будет ошибка вида 
"Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'task_library.users.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by"

Переделай по тому же принципу, что я описал выше

2020-09-21 09:49 UTC, balesniy commented on frontend/models/UserForm.php
> +                ->having(['=', 'count(distinct uc.category_id)', count($this->categories)]); // todo не придумал как еще выбрать все категории
я так сделал сначала, но тогда я получу `any` а по заданию просят `every` если я правильно понял фразу "все фильтры одновременно", вроде в sql была конструкция `all in` погуглю еще

2020-09-21 14:00 UTC, balesniy commented on frontend/models/UserForm.php
> +                ->having(['=', 'count(distinct uc.category_id)', count($this->categories)]); // todo не придумал как еще выбрать все категории
не придумал ничего толкового, или подзапросы делать со счетчиком, или отдельную таблицу под выбранные категории и джоины, мне нужна помощь )

2020-09-23 05:22 UTC, frexin requested changes

2020-09-23 05:22 UTC, frexin commented on frontend/models/UserForm.php
> +        if ($this->hasFeedback) {
Слушай, я только сейчас заметил, что у тебя это поле используется неправильно. Ты определяешь связь с таблицей откликов пользователей на задание, а тебе нужна другая сущность - отклики заказчиков об исполнителях. 
Тебе необходимо создать эту новую таблицу, модель для нее, определить связь и здесь заменить джойн.

2020-09-25 06:46 UTC, frexin requested changes

2020-09-25 06:46 UTC, frexin commented on frontend/models/UserForm.php
> +            $users->andWhere(['is not', 'c.task_id', null]);
Это что и зачем?
Не вижу, чтобы ты добавил новую таблицу, сущность и описал здесь связь.

2020-09-25 06:50 UTC, balesniy commented on frontend/models/UserForm.php
> +            $users->andWhere(['is not', 'c.task_id', null]);
таблица у меня была, я по отзывам сортирую, связь выше уже установлена, там left join чтобы показать всех пользователей, поэтому тут мне достаточно фильтра

2020-09-25 06:55 UTC, frexin commented on frontend/models/UserForm.php
> +            $users->andWhere(['is not', 'c.task_id', null]);
Как называется эта таблица и модель для нее?

2020-09-25 06:58 UTC, balesniy commented on frontend/models/UserForm.php
> +            $users->andWhere(['is not', 'c.task_id', null]);
https://github.com/htmlacademy-yii/221665-task-force-1/blob/master/schema.sql#L138 https://github.com/balesniy/221665-task-force-1/blob/module6-task1/frontend/models/Comments.php#L17

2020-09-25 07:07 UTC, frexin commented on frontend/models/UserForm.php
> +            $users->andWhere(['is not', 'c.task_id', null]);
Тогда все ок. Не заметил, что comments - это про отзывы

2020-09-25 07:07 UTC, merged

2020-09-25 07:11 UTC, balesniy commented on frontend/models/UserForm.php
> +            $users->andWhere(['is not', 'c.task_id', null]);
да, я с самого начала перепутал отклики и отзывы