Module1 task2
htmlacademy-yii/221665-task-force-1 pull request #2
Opened 2020-07-23 08:32 UTC by balesniy

2020-07-23 10:40 UTC, frexin commented
В классе отсутствует:
- метод для получения всех доступных действий на текущем статусе
- метод для получения следующего статуса
- не забудь про необходимость учитывать id исполнителя и заказчика в задаче, чтобы определять доступные действия

Пока твой класс не содержит никаких методов и является просто хранилищем списков. Надо это исправить.

2020-07-23 10:43 UTC, frexin requested changes
Надо исправить по комментарию выше

2020-07-26 12:56 UTC, frexin commented
Предлагаю обсудить решение этого задания в tg: tg.me/frexin

2020-07-31 14:05 UTC, merged

2021-05-25 10:41 UTC, mihan007 reviewed
Алексей, отличная работа. Отполируем до идеала. Написал свои мысли, изучи, пожалуйста.

2021-05-25 10:41 UTC, mihan007 commented on src/Task.php
> +class Task
Есть пару вариантов работы с константами
1. Создать в корне проекта папку Constants и в ней уже разместить набор классов, в которых будут значения. Класс сделать final, чтобы ясно дать понять, что он уже не расширяемый. Будет что-то вроде
```
final class TaskStatus
{
    const STATUS_NEW = 'new';
    const STATUS_CANCEL = 'cancel';
    const STATUS_WORK = 'work';
    const STATUS_DONE = 'done';
    const STATUS_FAIL = 'fail';
}
```
2. А вообще по красоте я бы сделал такие константы через https://github.com/spatie/enum. Это даст удобное автодополнение и строгую типизацию. Как следствие - меньше ошибок. К тому же, в php 8.1 приедут нативные enum и можно будет легко на них перейти

2021-05-25 10:41 UTC, mihan007 commented on src/Task.php
> +    const STATUS_NAME = [
Тут хорошо подойдет https://github.com/spatie/enum#enum-values

2021-05-25 10:41 UTC, mihan007 commented on src/Task.php
> +    const ACTION_NAME = [
https://github.com/spatie/enum#enum-values

2021-05-25 10:41 UTC, mihan007 commented on src/Task.php
> +    const status_map = [
1. Тут ты реализуешь паттерн State Machine. Его интересно реализовать самому. Я бы поглядел еще в https://symfony.com/doc/current/workflow/workflow-and-state-machine.html и http://yohan.giarel.li/Finite/ для вдохновения
2. Сразу используй PSR-12, настрой его в PhpStorm и автоформатируй под него весь код при commit. В нем, в частности, через _ пишутся только константы и названия полей модели. Остальное - camelCase.

2021-05-25 10:41 UTC, mihan007 commented on src/Task.php
> +    const action_map = [
1. PSR-12 naming conventions
2. Может быть выделить отдельно state machine для заказчика и исполнителя? Это проще удержать в голове.

2021-05-25 10:41 UTC, mihan007 commented on src/Task.php
> +    public function get_action($id)
1. PSR-12 naming conventions
2. Вообще непонятно, что делает функция. Если возвращает следующий статус, то я бы назвал что-то вроде `getNextAction($currentStatus)`. Так как статусов ограниченное число, то вполне возможно, что подойдет https://github.com/spatie/enum#enum-values
3. Должен быть возвращаемый тип у каждой функции. Возможно тут будет Enum из https://github.com/spatie/enum#enum-values

2021-05-25 10:41 UTC, mihan007 commented on src/Task.php
> +    public function get_user_status($id)
1. PSR-12 naming conventions
2. Что такое id на входе? $userId? $taskId? рекомендую называть более выразительно, чтобы прочитав сигнатуру функции, ты сам или твой коллега сразу понимал, что и как

2021-05-25 10:41 UTC, mihan007 commented on src/Task.php
> +    public static function get_next_status($action)
Почитай про понятие "конечный автомат". Это по сути диаграмма, где есть состояние сущности и переходы между этими состояниями. Например, публикация в блоге может иметь состояние "черновик", "на проверке у редактора", "опубликована" и между этими состояниями будут переход. Черновик, например, сможет перейти в состояние на проверке у редактора. Но черновик не сможет быть сразу опубликован.

2021-05-25 10:41 UTC, mihan007 commented on src/Task.php
> +    public static function getStatusMap()
а точно внешнему миру надо так глубоко в этот класс лезть? для чего?

2021-05-25 10:41 UTC, mihan007 commented on src/Task.php
> +    public static function getActionMap()
а точно внешнему миру надо так глубоко в этот класс лезть? для чего?

2021-05-25 10:41 UTC, mihan007 commented on src/Task.php
> +    public $customer_id;
определения полей класса всегда идет в начале класса. еще до конструктора

2021-05-25 10:41 UTC, mihan007 commented on src/Task.php
> +    public function __construct($status, $customer_id, $executor_id = null)
1. конструктор в самом вверху.
2. необходимо типизировать входные параметры. $status у тебя будет enum, а остальные 2 int. Это обезопасит тебя от ошибочных входных данных

2021-05-25 10:41 UTC, mihan007 commented on src/task_test.php
> +$task = new Task(1,1);
`1,1` это прям магия, магия. что за 1? лучше вынеси их в начало теста. напиши примерно
```
$status = TaskStatusEnum::NEW();
$customerId = 1
$task = new Task($status, $customerId);
```

2021-05-25 10:41 UTC, mihan007 commented on src/task_test.php
> +assert($task->buyer_id == 1444, 'хранит buyer id');
- что есть buyer_id? не видел его в классе.
- почему он должен быть равен 1444?
- что вообще такое 1444?

2021-05-25 10:41 UTC, mihan007 commented on src/task_test.php
> +assert(Task::action_map[Task::STATUS_CANCEL] == null, 'содержит status cancel');
тут тоже не очень понятно что происходит. класс обращается к `Task::action_map`. А что это такое? Может быть лучше обратиться к методу Task? И получится что-то вроде
```
$currentStatus = Task::STATUS_CANCEL;
assert($task->getNextAction($currentStatus) === null, 'содержит status cancel');
```