добавляет схему БД
htmlacademy-yii/221665-task-force-1 pull request #4
Opened 2020-08-16 16:38 UTC by balesniy

2020-08-17 06:50 UTC, frexin requested changes

2020-08-17 06:50 UTC, frexin commented on schema.sql
> +CREATE DATABASE task_library
Посмотри в ТЗ - для проекта используется БД MySQL

2020-08-17 06:50 UTC, frexin commented on schema.sql
> +    latitude FLOAD,
Что за `FLOAD`?

2020-08-17 06:50 UTC, frexin commented on schema.sql
> +    category_id INTEGER,
Категория обязательна

2020-08-17 06:50 UTC, frexin commented on schema.sql
> +CREATE TABLE responses
У отклика должен быть комментарий

2020-08-17 06:50 UTC, frexin commented on src/Model/Response.php
> +    public function changeStatus($status)
О каком статусе отклика идет речь?

2020-08-17 14:11 UTC, frexin requested changes

2020-08-17 14:11 UTC, frexin commented on schema.sql
> +CREATE DATABASE IF NOT EXISTS task_library;
Добавь указание кодировки

2020-08-17 14:11 UTC, frexin commented on schema.sql
> +  FOREIGN KEY (city_id) REFERENCES cities (id)
здесь и далее внешний ключ не создается из за несовпадения типов

2020-08-18 14:02 UTC, merged

2021-05-30 07:49 UTC, mihan007 commented
@balesniy все гуд!